name: Build and Deploy Discord Bot

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  NODE_VERSION: '22'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Bot

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build TypeScript
        run: yarn build-tsup  # Adjust if you have a different build command

      - name: Run post build to get gongo
        run: yarn postbuild

      - name: Create ZIP Archive of Build
        run: zip -r bot-build.zip dist/

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: bot-build
          path: bot-build.zip  # Upload only the zip file to reduce file count

  deploy:
    runs-on: ubuntu-latest
    name: Deploy Bot to Azure VM
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: bot-build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Azure VM
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USER: ${{ secrets.SSH_USER }}
          PM2_APP_NAME: buce-helpers
        run: |
          echo "Connecting to Azure VM"
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            # Add NVM binaries to PATH
            export PATH=$PATH:/home/rafael52468/.nvm/versions/node/v22.9.0/bin

            # Source NVM script to load Node.js environment
            [ -s "$HOME/.nvm/nvm.sh" ] && \. "$HOME/.nvm/nvm.sh"

            # Confirm that the project directory exists
            cd /home/rafael52468/bh/bruce_helper  # Update with the correct path

            # Pull the latest changes from GitHub
            git pull origin main || git pull origin master

            # Install dependencies
            yarn install --frozen-lockfile

            # Build TypeScript files
            yarn build-tsup

            yarn postbuild

            pm2 describe $PM2_APP_NAME || echo "Process not found, starting a new one."

            # Start or reload the bot process with PM2
            pm2 reload $PM2_APP_NAME --update-env || pm2 start dist/index.js --name $PM2_APP_NAME

            # Save PM2 state
            pm2 save
          EOF